[package]
name = "black/roblox-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

[dev-dependencies]
Rewire = "sayhisam1/rewire@0.3.0"